-- Zoom / Microsoft Teams academy integration — additive schema.
-- Applied automatically by Netlify Database on deploy.
--
-- This migration is written against the schema that is actually live in this
-- project's database, which stores every primary/foreign key as TEXT (uuids
-- generated by the app) and every timestamp as TEXT holding an ISO-8601 string.
-- New objects below follow that same convention so they line up with the
-- existing academies / courses / modules / users tables.
--
-- `academy_integrations` already exists, so it is only extended here (adding
-- the `status` column the admin UI reads). The `live_sessions` and
-- `oauth_states` tables are new.

-- Connection lifecycle state, read by the admin integrations page and set when
-- an admin disconnects or a token refresh fails. Existing rows are, by
-- definition, connected — hence the default.
ALTER TABLE academy_integrations
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'connected';

CREATE TABLE IF NOT EXISTS live_sessions (
  id TEXT PRIMARY KEY,
  academy_id TEXT NOT NULL REFERENCES academies(id) ON DELETE CASCADE,
  course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  module_id TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  academy_integration_id TEXT NOT NULL REFERENCES academy_integrations(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('zoom', 'teams')),
  external_meeting_id TEXT,
  join_url TEXT,
  host_url TEXT,
  topic TEXT,
  start_time TEXT,
  duration_minutes INTEGER,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'cancelled', 'completed')),
  created_at TEXT NOT NULL
);

-- Sessions are always listed for one module at a time.
CREATE INDEX IF NOT EXISTS live_sessions_module_id_idx ON live_sessions (module_id);

CREATE TABLE IF NOT EXISTS oauth_states (
  state TEXT PRIMARY KEY,
  academy_id TEXT NOT NULL REFERENCES academies(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('zoom', 'teams')),
  user_id TEXT REFERENCES users(id),
  created_at TEXT NOT NULL
);

-- oauth_states rows are single-use and short-lived; optionally add a cron/cleanup
-- job to delete rows older than ~1 hour if this table grows unbounded.
